from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from replay_demo import (
    SERVICES,
    Evidence,
    replay_project_1,
    replay_project_2,
    reserve_port,
    start_service,
    wait_for_health,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = ROOT / "out"


def stop_processes(processes: list[subprocess.Popen]) -> None:
    for process in processes:
        if process.poll() is None:
            process.terminate()
    for process in processes:
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=5)


def render_markdown(created_at: str, urls: list[str], evidence: list[Evidence]) -> str:
    passed = sum(1 for item in evidence if item.passed)
    rows = [
        "| Status | Evidence | Detail |",
        "| --- | --- | --- |",
    ]
    for item in evidence:
        status = "PASS" if item.passed else "FAIL"
        rows.append(f"| {status} | {item.label} | `{item.detail}` |")

    return "\n".join(
        [
            "# Demo Replay Artifact",
            "",
            "Generated by: `python -B scripts/dev.py replay-artifact`",
            "",
            f"Created at: `{created_at}`",
            "",
            "## Demo URLs",
            "",
            f"- Secure Enterprise Knowledge Copilot: `{urls[0]}`",
            f"- Regulated Customer Operations Agent: `{urls[1]}`",
            "",
            "## Summary",
            "",
            f"- Replay checks: {passed}/{len(evidence)} passed",
            "- Project 1 proves permission-aware RAG, citation-backed answers, abstention, and prompt-injection handling.",
            "- Project 2 proves governed tool use, approval queue behavior, side-effect blocking, and audit surfaces.",
            "",
            "## Evidence",
            "",
            *rows,
            "",
            "## Release Use",
            "",
            "Attach this artifact to a release or paste it into interview notes after regenerating it from the same commit.",
            "The generated files live under `out/`, which is intentionally ignored by Git.",
            "",
        ]
    )


def write_artifacts(out_dir: Path, created_at: str, urls: list[str], evidence: list[Evidence]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_by": "python -B scripts/dev.py replay-artifact",
        "created_at": created_at,
        "urls": {
            "secure-enterprise-knowledge-copilot": urls[0],
            "regulated-customer-operations-agent": urls[1],
        },
        "passed": sum(1 for item in evidence if item.passed),
        "total": len(evidence),
        "evidence": [asdict(item) for item in evidence],
    }
    (out_dir / "demo_replay_artifact.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    (out_dir / "demo_replay_artifact.md").write_text(
        render_markdown(created_at, urls, evidence),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate release-attachable replay evidence under out/ without modifying tracked docs.",
    )
    parser.add_argument("--project1-port", type=int, default=SERVICES[0].preferred_port)
    parser.add_argument("--project2-port", type=int, default=SERVICES[1].preferred_port)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args()

    ports = [reserve_port(args.project1_port), reserve_port(args.project2_port)]
    urls = [f"http://127.0.0.1:{port}" for port in ports]
    processes: list[subprocess.Popen] = []
    evidence: list[Evidence] = []
    created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    try:
        for service, port in zip(SERVICES, ports):
            print(f"Starting {service.name} on port {port} with reset state")
            processes.append(start_service(service, port))

        for service, url in zip(SERVICES, urls):
            if not wait_for_health(url):
                print(f"Service did not become healthy: {service.name} ({url})", file=sys.stderr)
                return 1

        evidence.extend(replay_project_1(urls[0]))
        evidence.extend(replay_project_2(urls[1]))
        write_artifacts(args.out_dir, created_at, urls, evidence)
    finally:
        stop_processes(processes)

    passed = sum(1 for item in evidence if item.passed)
    print(f"Replay artifact checks: {passed}/{len(evidence)} passed")
    print(f"Wrote {args.out_dir / 'demo_replay_artifact.md'}")
    print(f"Wrote {args.out_dir / 'demo_replay_artifact.json'}")
    return 0 if evidence and passed == len(evidence) else 1


if __name__ == "__main__":
    raise SystemExit(main())
