from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "docs" / "demo_report.md"


def run_command(args: list[str]) -> tuple[int, str, str]:
    result = subprocess.run(args, cwd=ROOT, text=True, capture_output=True)
    return result.returncode, result.stdout, result.stderr


def parse_eval_summaries(output: str) -> list[str]:
    summaries: list[str] = []
    current_name: str | None = None
    current_lines: list[str] = []

    def flush() -> None:
        nonlocal current_name, current_lines
        if not current_name or not current_lines:
            return
        payload = json.loads("\n".join(current_lines))
        metrics = payload["metrics"]
        parts = [
            f"{current_name}: {metrics['passed_cases']}/{metrics['total_cases']} passed",
            f"pass_rate = {metrics['pass_rate']}",
        ]
        if "unsafe_leak_failures" in metrics:
            parts.append(f"unsafe_leak_failures = {metrics['unsafe_leak_failures']}")
        if "unsafe_direct_side_effect_failures" in metrics:
            parts.append(
                f"unsafe_direct_side_effect_failures = {metrics['unsafe_direct_side_effect_failures']}"
            )
        summaries.append("- " + ", ".join(parts))
        current_name = None
        current_lines = []

    for raw_line in output.splitlines():
        line = raw_line.strip()
        if line.startswith("===") and line.endswith("==="):
            flush()
            current_name = line.strip("= ").strip()
            current_lines = []
        elif current_name and line:
            current_lines.append(raw_line)
    flush()
    return summaries


def parse_smoke_summary(output: str) -> str:
    match = re.search(r"Smoke tests: \d+/\d+ passed", output)
    if match:
        return match.group(0)
    return "Smoke test summary unavailable"


def main() -> int:
    health_code, health_out, health_err = run_command([sys.executable, "-B", "scripts/check_health.py"])
    eval_code, eval_out, eval_err = run_command([sys.executable, "-B", "scripts/run_all_evals.py"])
    smoke_code, smoke_out, smoke_err = run_command([sys.executable, "-B", "scripts/smoke_test_demo_flows.py"])

    status = "PASS" if health_code == 0 and eval_code == 0 and smoke_code == 0 else "FAIL"
    eval_summaries = parse_eval_summaries(eval_out) if eval_code == 0 else []
    smoke_summary = parse_smoke_summary(smoke_out)
    failure_details = ""
    if status != "PASS":
        failure_details = f"""
## Failure Details

### Health

```text
{health_out.strip()}
{health_err.strip()}
```

### Evals

```text
{eval_out.strip()}
{eval_err.strip()}
```

### Smoke

```text
{smoke_out.strip()}
{smoke_err.strip()}
```
"""

    report = f"""# FDE Portfolio Demo Report

Generated by: `python -B scripts/dev.py report`

Overall status: **{status}**

## Demo URLs

- Secure Enterprise Knowledge Copilot: http://127.0.0.1:8765
- Regulated Customer Operations Agent: http://127.0.0.1:8770

## Health Check

```text
{health_out.strip()}
{health_err.strip()}
```

## Eval Gate

{chr(10).join(eval_summaries) if eval_summaries else "- Eval summary unavailable"}

## Smoke Test Business Flows

```text
{smoke_summary}
```

{failure_details}

## Demo Narrative

Project 1 proves secure enterprise RAG:

- role-aware retrieval
- citation enforcement
- abstention for inaccessible or unsupported answers
- prompt-injection handling
- trace and audit records

Project 2 proves governed agentic operations:

- tool calling against business objects
- internal action automation
- human approval queue for external side effects
- direct side-effect blocking
- supervisor-only approval
- trace and audit records

## Recommended Interview Flow

1. Open Project 1 and show Alice remote-work answer with HR citation.
2. Ask Alice for the finance plan and show abstention.
3. Switch to Morgan and show finance citation.
4. Run Project 1 evals.
5. Open Project 2 and run Market Blue investigation.
6. Show approval request and blocked direct `send_notice`.
7. Approve as supervisor and show audit.
8. Run Project 2 evals.

"""
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
